---
- hosts: web
  vars:
   - docroot: /var/www/html/test.com

  tasks:
   - name: Add epel repo
     yum_repository:
       name: epel
       description: EPEL YUM repo
       baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
     register: addedrepo

   - name: Install Httpd ting
     yum: name=httpd state=installed update_cache=true
     when: addedrepo is succeeded 
     register: httpdinstalled
     notify:
      - Start Httpd

   - name: Create Web Root
     when: httpdinstalled is succeeded
     file: dest={{docroot}} mode=775 state=directory owner=apache group=apache
     notify:
      - Reload Httpd

  handlers:
   - name: Start Httpd
     service: name=httpd state=started

   - name: Reload Httpd
     service: name=httpd state=reloaded
