---
- hosts: kvm-db4
  gather_facts: "no"
  become: yes
  become_user: root

  vars_files:
    - "vars/private.yml"
    - "vars/vault.yml"
  roles:
     - users
#     - httpd
     - network
     - database    
