---
# tasks file for database

- include_tasks: nfs.yml 

- include_tasks: ssmtp.yml

- name: Copy yum repo
  ansible.builtin.copy:
    src: mariadb.repo
    dest: /etc/yum.repos.d/mariadb.repo
    owner: root
    group: root
    mode: '0644'
  register: copyrepo

- name: makecache
  command: yum makecache --disablerepo='*' --enablerepo='mariadb'
  when: copyrepo is succeeded
  register: makecache

- name: Install MariaDB
  yum:
    name:
      - MariaDB-server
      - MariaDB-client
      - zip
      - unzip
#      - epel-release
    state: installed 
  when: makecache is succeeded
  register: install_db
  notify:
   - Start mariadb
   - Enable mariadb

#- name: refresh yum repolist for epel
#  command: yum repolist
#  register: refresh_repolist
#
#- name: Install ssmtp
#  yum:
#    name: ssmtp
#    state: installed
#  when: refresh_repolist is succeeded 
