---

- name: Install nfs
  yum: name=nfs-utils state=installed update_cache=true
  register: nfs_installed

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  when: nfs_installed is succeeded
  register: dir_created
  with_items:
    - /db-backups
    - /root/scripts

- name: Edit fstab
  lineinfile:
    path: /etc/fstab
    state: present
    line: kvm-db-backup:/db-backups       /db-backups     nfs     nosuid,rw,sync,hard,intr  0  0
  when: dir_created is succeeded
  register: fstab_updated

- name: mount directory
  command: mount -a
  when: fstab_updated is succeeded

- name: Copy script
  copy:
    src: mysqlbackup.sh
    dest: /root/scripts
    mode: '0755'
  register: copy_script

- name: cronjob
  cron:
    name: mysqldump
    weekday: "*"
    minute: "0"
    hour: "21"
    user: root
    job: /root/scripts/mysqlbackup.sh
    cron_file: mysqlbackupjob
    state: present
  when: copy_script is succeeded


- name: add path variable to cronjob
  cronvar:
    name: PATH
    value: /sbin:/bin:/usr/sbin:/usr/bin
    cron_file: mysqlbackupjob
    state: present
